### ISSUE TITLE
LoadError on Ruby 2.0.0p247 and Windows 10

### ISSUE THREAD

**Issue by ruggieroguida** [mieko/rbclipper#9]
I am using Ruby 2.0.0p247 (64bit) and corresponding DevKit on Window 10. I am try to install with `gem install clipper` and everything seems to work.

However when I try to require it I have the error:

```
LoadError: 193: %1 is not a valid Win32 application.   - C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/clipper-2.9.1/lib/clipper.so
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from (irb):1
        from C:/Ruby200-x64/bin/irb:12:in `<main>'
```

Other gems work normally as expected.

**Comment by treenewbee** [comment]
Did a c library upgrade to the latest version but didn't realize constant/function names even implementation have changed, but here is a fixed and working version : 

https://github.com/treenewbee/rbclipper

This has been merged here: 

https://rubygems.org/gems/ruby_clipper

**Comment by ruggieroguida** [comment]
I have tried both, same problem.

First link with `rake install` and second link with `gem install ruby_clipper`

**Comment by mieko** [comment]
Is ruby_clipper considered the most-maintained fork?  I'd like to point people to one that's more active.

**Comment by mieko** [comment]
And if there's a consensus, transfer ownership of the gem name, etc.

**Comment by treenewbee** [comment]
I believe so.
